[2019-11-26 21:27:13,277] {taskinstance.py:630} INFO - Dependencies all met for <TaskInstance: project_pipeline.generate_advanced_features 2019-11-26T20:24:39.688462+00:00 [queued]>
[2019-11-26 21:27:13,306] {taskinstance.py:630} INFO - Dependencies all met for <TaskInstance: project_pipeline.generate_advanced_features 2019-11-26T20:24:39.688462+00:00 [queued]>
[2019-11-26 21:27:13,306] {taskinstance.py:841} INFO - 
--------------------------------------------------------------------------------
[2019-11-26 21:27:13,307] {taskinstance.py:842} INFO - Starting attempt 1 of 1
[2019-11-26 21:27:13,307] {taskinstance.py:843} INFO - 
--------------------------------------------------------------------------------
[2019-11-26 21:27:13,446] {taskinstance.py:862} INFO - Executing <Task(PythonOperator): generate_advanced_features> on 2019-11-26T20:24:39.688462+00:00
[2019-11-26 21:27:13,446] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'project_pipeline', 'generate_advanced_features', '2019-11-26T20:24:39.688462+00:00', '--job_id', '21', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/project_pipeline.py', '--cfg_path', '/tmp/tmpmorp02ds']
[2019-11-26 21:27:15,108] {base_task_runner.py:115} INFO - Job 21: Subtask generate_advanced_features [2019-11-26 21:27:15,106] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-11-26 21:27:15,108] {base_task_runner.py:115} INFO - Job 21: Subtask generate_advanced_features [2019-11-26 21:27:15,108] {dagbag.py:92} INFO - Filling up the DagBag from /home/exceptions/mlprojects/Airflow/sendyproject/dags/project_pipeline.py
[2019-11-26 21:27:15,737] {base_task_runner.py:115} INFO - Job 21: Subtask generate_advanced_features [2019-11-26 21:27:15,736] {cli.py:545} INFO - Running <TaskInstance: project_pipeline.generate_advanced_features 2019-11-26T20:24:39.688462+00:00 [running]> on host exceptions
[2019-11-26 21:27:15,748] {python_operator.py:105} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=project_pipeline
AIRFLOW_CTX_EXECUTION_DATE=2019-11-26T20:24:39.688462+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2019-11-26T20:24:39.688462+00:00
AIRFLOW_CTX_TASK_ID=generate_advanced_features
[2019-11-26 21:27:18,159] {logging_mixin.py:112} INFO - [2019-11-26 21:27:18,159] {local_task_job.py:124} WARNING - Time since last heartbeat(0.01 s) < heartrate(5.0 s), sleeping for 4.994599 s
[2019-11-26 21:27:23,397] {logging_mixin.py:112} INFO - [2019-11-26 21:27:23,397] {local_task_job.py:124} WARNING - Time since last heartbeat(0.01 s) < heartrate(5.0 s), sleeping for 4.99057 s
[2019-11-26 21:27:27,974] {python_operator.py:114} INFO - Done. Returned value was: <feature_engineering.Generate_advanced_features object at 0x7ff51c4f2438>
[2019-11-26 21:27:28,437] {base_task_runner.py:115} INFO - Job 21: Subtask generate_advanced_features /home/exceptions/env/lib/python3.5/site-packages/airflow/configuration.py:627: DeprecationWarning: You have two airflow.cfg files: /home/exceptions/airflow/airflow.cfg and /home/exceptions/mlprojects/Airflow/sendyproject/airflow.cfg. Airflow used to look at ~/airflow/airflow.cfg, even when AIRFLOW_HOME was set to a different value. Airflow will now only read /home/exceptions/mlprojects/Airflow/sendyproject/airflow.cfg, and you should remove the other file
[2019-11-26 21:27:28,437] {base_task_runner.py:115} INFO - Job 21: Subtask generate_advanced_features   category=DeprecationWarning,
[2019-11-26 21:27:28,580] {logging_mixin.py:112} INFO - [2019-11-26 21:27:28,579] {local_task_job.py:167} WARNING - State of this instance has been externally set to success. Taking the poison pill.
[2019-11-26 21:27:28,601] {helpers.py:308} INFO - Sending Signals.SIGTERM to GPID 9985
[2019-11-26 21:27:28,611] {helpers.py:286} INFO - Process psutil.Process(pid=9985, status='terminated') (9985) terminated with exit code -15
[2019-11-26 21:27:28,613] {logging_mixin.py:112} INFO - [2019-11-26 21:27:28,613] {local_task_job.py:124} WARNING - Time since last heartbeat(0.05 s) < heartrate(5.0 s), sleeping for 4.949338 s
[2019-11-26 21:27:33,567] {logging_mixin.py:112} INFO - [2019-11-26 21:27:33,565] {local_task_job.py:103} INFO - Task exited with return code 0
